-- spec/015_protagonist_creation.md - PlayerCharacter にアイコンと基礎ステータス追加
ALTER TABLE "PlayerCharacter" ADD COLUMN "iconFilename" TEXT;
ALTER TABLE "PlayerCharacter" ADD COLUMN "STR" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "PlayerCharacter" ADD COLUMN "INT" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "PlayerCharacter" ADD COLUMN "DEX" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "PlayerCharacter" ADD COLUMN "VIT" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "PlayerCharacter" ADD COLUMN "SPD" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "PlayerCharacter" ADD COLUMN "LUK" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "PlayerCharacter" ADD COLUMN "CAP" INTEGER NOT NULL DEFAULT 60;
